# Generated by Django 4.2.7 on 2023-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
